import {StyleSheet} from 'react-native'
export default StyleSheet.create(
    {
       viewProducts:{
            elevation:10,
            borderRadius:7,
            backgroundColor:'white',
            height:170,
            marginBottom:2,  
        },
        Products:{
            elevation:10,
            borderRadius:7,
            backgroundColor:'white',
            height:300,
            marginBottom:2,  
        },
        viewPromo:{
            elevation:10,
            borderRadius:7,
            backgroundColor:'white',
            height:100,
            marginBottom:2,  
        },
        cartViewProduct:{
            elevation:10,
            borderRadius:7,
            backgroundColor:'white',
            height:170,
            marginBottom:2,
        },
        viewImage:{
            margin:5,
            width:'30%',
            height:'120%'
        },
        linearviewImage:{
            margin:5,
            width:'30%',
            height:'120%'
        },
        title:{
                
                fontSize:16,
                marginVertical:5,
                flexWrap:'wrap',
                overflow:'hidden',
        },
        promoText:{
            fontSize:18,
            marginBottom:10,
        }
        ,
        priceTag:{
            fontSize:14,
            color:'#888',
            marginHorizontal:5,
            textDecorationLine:'line-through'
        },
        price:{
            fontSize:16,
            marginHorizontal:10,
            
        },
        save:{
            fontSize:14,
            color:'maroon',
            marginHorizontal:5,
        },
        view:{
        
           justifyContent:'flex-end',
           alignItems:'flex-end',
           height:'25%',
           paddingHorizontal:20 
        },
        details:{
            height:'15%',
            padding:10
        },
        container:{
            width:'70%',
            height:'70%',
            borderRadius:40,
            overflow:'hidden',
            alignSelf:'center'
        },
        cart:{
            flexDirection:'row',
            backgroundColor:'purple',
            justifyContent:'space-between'
        }
        ,addcart:{
            flexDirection:'row',
            backgroundColor:'maroon',
            justifyContent:'space-between'
        },ValueAdd:{
            flexDirection:'row',
            justifyContent:'space-between',
            margin:5
        },
        tabView:{
            flexDirection:'row',justifyContent:'space-evenly',backgroundColor:'white',elevation:10
        },
        tabButton:{
            borderWidth:1,
            height:42,
            width:'40%',
            backgroundColor:"white",
            alignItems:'center'
           
        },
        modal:
        {
            top:300,
             alignSelf:'flex-start',
             flex:0.1,
             padding:100,
            backgroundColor:'purple'
        },
        modalText:{
            fontSize:20,
            color:'white',
            margin:5
        },
        icon:{
            alignItems:'center',
            textAlign:"center",
            flexDirection:'row'
          },
          sortingcontainer:{
            flexDirection:'row',
            justifyContent:'space-between',
            color:'#fff8dc',
            backgroundColor:'purple'
          },
          item:{
            fontSize:26,
            color:'white'
          }
    })